# Generated by Django 4.1.4 on 2022-12-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_obrok_obrok_od_osobe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namirnica',
            name='namirnica_meso',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='namirnica',
            name='namirnica_povrce',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='namirnica',
            name='namirnica_voce',
            field=models.CharField(max_length=30),
        ),
    ]
