# Generated by Django 4.1.4 on 2022-12-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_namirnica_namirnica_meso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrok',
            name='obrok_dorucak',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='obrok',
            name='obrok_rucak',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='obrok',
            name='obrok_uzina',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='obrok',
            name='obrok_vecera',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='obrok',
            name='obrok_zajutrak',
            field=models.CharField(max_length=50),
        ),
    ]
