# Generated by Django 4.1.4 on 2022-12-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_obrok_obrok_dorucak_alter_obrok_obrok_rucak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namirnica',
            name='namirnica_meso',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='namirnica',
            name='namirnica_povrce',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='namirnica',
            name='namirnica_voce',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='obrok',
            name='obrok_dorucak',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='obrok',
            name='obrok_rucak',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='obrok',
            name='obrok_uzina',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='obrok',
            name='obrok_vecera',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='obrok',
            name='obrok_zajutrak',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
